config/routes.rb
Tradr::Application.routes.draw do



  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

  resources :user_sessions
  resources :users do
    resources :stocks
  end


  root :to => 'users#index'


end

app/models/stock.rb
class Stock < ActiveRecord::Base
  belongs_to :user
  attr_accessible :quantity, :starting_price, :symbol, :user_id

  before_create :set_starting_price

   def set_starting_price
     # quote = StockQuote::Stock.quote(symbol)
     # self.starting_price = quote.last

     quote = Ystock.get_stock(symbol).first[1]
     self.starting_price = quote[:price]
   end

   def latest_price
    # quote = StockQuote::Stock.quote(symbol)
    # quote.last

    quote = Ystock.get_stock(symbol).first[1]
    quote[:price]
   end



end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  attr_accessible :email, :password, :password_confirmation, :cash

  has_many :stocks

  validates_length_of :password, :minimum => 3, :message => "password must be at least 3 characters long", :if => :password
  validates_confirmation_of :password, :message => "should match confirmation", :if => :password
  validates_uniqueness_of :email

  def stock_profit(stock)
    paid_initially = stock.starting_price

    latest_value_of_shares = stock.latest_price
    (latest_value_of_shares.to_f - paid_initially.to_f) * stock.quantity
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :require_login

  protected

  def not_authenticated
    redirect_to login_path, :alert => "Please login first."
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  # GET /stocks
  # GET /stocks.json
  def index
    @user = User.find(session[:user_id])
    @stocks = @user.stocks

    respond_to do |format|
      format.html # index.html.erb
      format.js
    end
  end

  # GET /stocks/1
  # GET /stocks/1.json
  def show
    @user = User.find(session[:user_id])
    @stock = Stock.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @stock }
    end
  end

  # GET /stocks/new
  # GET /stocks/new.json
  def new
    @user = User.find(session[:user_id])
    @stock = Stock.new

    respond_to do |format|
      format.html # new.html.erb
      format.js
    end
  end

  # GET /stocks/1/edit
  def edit
    @user = User.find(session[:user_id])
    @stock = Stock.find(params[:id])
  end

  # POST /stocks
  # POST /stocks.json
  def create
    @user = User.find(session[:user_id])
    @stock = Stock.new(params[:stock])

    # another format I could have used to avoid the hidden user_id field in the view, use:
    # @stock = current_user.stocks.build(params[:stock])
    # @stock.save

    respond_to do |format|
      if @stock.save

        @stocks = @user.stocks
        format.html { redirect_to @stock, notice: 'Stock was successfully created.' }
        format.js
      else
        format.html { render action: "new" }
        format.js
      end
    end
  end

  # PUT /stocks/1
  # PUT /stocks/1.json
  def update
    @stock = Stock.find(params[:id])

    respond_to do |format|
      if @stock.update_attributes(params[:stock])
        format.html { redirect_to @stock, notice: 'Stock was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1
  # DELETE /stocks/1.json
  def destroy
    @stock = Stock.find(params[:id])
    @stock.destroy

    respond_to do |format|
      format.html { redirect_to user_stocks_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController

  skip_before_filter :require_login, :except => [:destroy]

  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.js
    end
  end

  def create
    respond_to do |format|
      if @user = login(params[:email],params[:password])
        format.html { redirect_back_or_to(:users, :notice => 'Login successful.') }
        format.js
      else
        format.html { flash.now[:alert] = "Login failed."; render :action => "new" }
        format.xml { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    logout
    redirect_to(:users, :notice => 'Logged out!')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_filter :require_login, :only => [:index, :new, :create]

  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.js
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to(:users, :notice => 'User was successfully created.') }
        format.js
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_nav.html.erb
<ul class="title-area">
  <li class="name">
    <h1><%= link_to "Tradr", root_path %></a></h1>
  </li>
</ul>

<section class="top-bar-section">
  <ul class="right">
    <li class="divider"></li>
    <% if current_user %>
      <li><%= link_to "Logged in: #{current_user.email}", edit_user_path(current_user.id) %></li>
      <li><%= link_to "Your Stocks", user_stocks_path(current_user.id) %></li>
      <li class="divider"></li>
      <li><%= link_to "Logout", :logout %></li>
    <% else %>
      <li><%= link_to "Register", new_user_path, :remote => true, :data => {"reveal-id" => "signup_window"} %></li>
      <li class="divider"></li>
      <li><%= link_to "Login", :login, :remote => true, :data => {"reveal-id" => "login_window"} %></li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
  	<meta charset="utf-8" />

  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Tradr" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <nav class="top-bar">
      <%= render 'layouts/nav' %>
    </nav>

    <div id="signup_window" class="reveal-modal medium"></div>
    <div id="login_window" class="reveal-modal medium"></div>

    <% if !notice.blank? || !alert.blank? %>
      <div class="row">
        <div class="large-12 large-centered columns">
          <% if !notice.blank? %>
            <div class="alert-box success" id="notice"><%= notice %></div>
          <% end %>

          <% if !alert.blank? %>
            <div class="alert-box alert" id="alert"><%= alert %></div>
          <% end %>
        </div>
      </div>
    <% end %>

<div class="row">
  <div class="large-12 columns">
    <%= yield %>
  </div>
</div>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
    <script src="http://cdn.oesmith.co.uk/morris-0.4.3.min.js"></script>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/stocks/_form.html.erb
<div class="row">
  <div class="large-3 columns">
    <%= form_for [@user, @stock], :remote => true do |f| %>
      <% if @stock.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

          <ul>
          <% @stock.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= f.text_field :symbol, :placeholder => "symbol" %>
      </div>
      <div class="field">
        <%= f.number_field :quantity, :placeholder => "quantity" %>
      </div>
     <!--  <div class="field">
        <%#= f.label :starting_price %><br />
        <%#= f.text_field :starting_price %>
      </div> -->
      <div class="field">
        <%= f.hidden_field :user_id, :value => current_user.id %>
      </div>
      <div class="actions">
        <%= f.submit "Buy", :class => "button" %>
      </div>
    <% end %>
  </div>
</div>

app/views/stocks/_stocks.html.erb
<table>
  <tr>
    <th>Symbol</th>
    <th>Quantity</th>
    <th>Starting price</th>
    <th>Current Trading Price</th>
    <th>Gross Profit</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @stocks.each do |stock| %>
  <tr>
    <td><%= stock.symbol %></td>
    <td><%= stock.quantity %></td>
    <td><%= number_to_currency(stock.starting_price) %></td>
    <td><%= number_to_currency(stock.latest_price) %></td>
    <td><%= number_to_currency(current_user.stock_profit(stock)) %></td>
    <td><%= link_to 'Show', user_stock_path(current_user.id, stock.id) %></td>
    <td><%= link_to 'Edit', edit_user_stock_path(current_user.id, stock.id) %></td>
    <td><%= link_to 'Destroy', user_stock_path(current_user.id, stock.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

app/views/stocks/create.js.erb
var stocks_table = $('#stocks_table');

$('#new_stock > div').remove();
$('#new_stock').show();

stocks_table.empty().append("<%= j render 'stocks' %>");

app/views/stocks/edit.html.erb
<h1>Editing stock</h1>

<%= render 'form' %>

app/views/stocks/index.html.erb
<h1>Listing stocks</h1>
<h2>Cash on hand: <%= number_to_currency(@user.cash) %></h2>

<%= link_to "Refresh", user_stocks_path, :class => "button success", :remote => true %>

<div id="stocks_table">
  <%= render "stocks" %>
</div>

<h2>Add a New Stock</h2>

<div>
  <%= link_to "Add Stock", new_user_stock_path, :id => "new_stock", :class => "button", :remote => true %>
</div>

<br />

app/views/stocks/index.js.erb
var stocks_table = $('#stocks_table');


stocks_table.html("<%= j render 'stocks' %>");

// consider setting an interval so its automatic

app/views/stocks/new.js.erb
var new_stock = $('#new_stock');

new_stock.hide();

new_stock.parent().append("<%= j render 'form' %>");

app/views/stocks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Symbol:</b>
  <%= @stock.symbol %>
</p>

<p>
  <b>Quantity:</b>
  <%= @stock.quantity %>
</p>

<p>
  <b>Starting price:</b>
  <%= @stock.starting_price %>
</p>

<p>
  <b>User:</b>
  <%= @stock.user.email %>
</p>


<%= link_to 'Back', user_stocks_path %>

app/views/user_sessions/_form.html.erb
<%= form_tag user_sessions_path, :method => :post, :remote => true do %>
  <div class="field">
    <%= label_tag :email %><br />
    <%= text_field_tag :email %>
  </div>
  <div class="field">
    <%= label_tag :password %><br />
    <%= password_field_tag :password %>
  </div>
  <div class="actions">
    <%= submit_tag "Login", :class => "button" %>
  </div>
<% end %>

app/views/user_sessions/create.js.erb
var nav = $('nav.top-bar');

$('#login_window').foundation('reveal', 'close');

nav.empty().append("<%= j render 'layouts/nav' %>");

app/views/user_sessions/new.js.erb
var login_window = $('#login_window');

login_window.html("<%= j render 'form' %>");

app/views/users/_form.html.erb
<%= form_for(@user, :remote => true) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
     <%= f.label :password %><br />
     <%= f.password_field :password %>
  </div>
  <div class="field">
     <%= f.label :password_confirmation %><br />
     <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :cash %><br />
    <%= f.text_field :cash %>
  </div>
  <div class="actions">
    <%= f.submit "Save", :class => "button" %>
  </div>
<% end %>

app/views/users/create.js.erb
$('#signup_window').foundation('reveal', 'close');

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Welcome to Tradr</h1>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/new.js.erb
var signup_window = $('#signup_window');

signup_window.html("<%= j render 'form' %>");

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Crypted password:</b>
  <%= @user.crypted_password %>
</p>

<p>
  <b>Salt:</b>
  <%= @user.salt %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>